apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/mualadin/flask-k8s-ci-cd
    argocd-image-updater.argoproj.io/update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ghcr.io/mualadin/flask-k8s-ci-cd:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: SECRET_KEY
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: APP_ENV
        volumeMounts:
        - name: flask-storage
          mountPath: /app/data
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: flask-pvc
